name: Dhayen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_background_service:
  flutter_local_notifications: ^9.9.1
  flutter_phone_direct_caller: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.1.0
  webview_flutter: ^3.0.4
  fluttertoast: ^8.0.8
  geocoder: ^0.2.1
  geolocator: ^5.1.1
  google_fonts: ^2.1.0
  location: ^2.3.5
  lottie: ^1.2.1
  #permission_handler: ^8.1.6
  permission_handler:
  pinput: ^1.2.1
  shake: ^2.1.0
  shared_preferences: ^2.0.5
  shared_preferences_android :
  shared_preferences_ios :
  telephony: ^0.1.4
  url_launcher: ^6.0.10
  vibration: ^1.7.3
  timelines: ^0.1.0
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  font_awesome_flutter: ^9.0.0
  flutter_rating_bar: ^4.0.0
  animations: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_markdown: ^0.6.10
  background_sms: ^0.0.4
  background_location: ^0.8.1
  workmanager: ^0.5.0
  firebase_performance: ^0.8.2+1
  get: ^4.6.5
  flutter_sound: ^9.2.13
  audio_background_record :
    path: ./plugins/audio_background_record
  easy_folder_picker: ^1.2.1
  duration_picker_dialog_box: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/
    - assets/onboarding/
    - assets/images/

  fonts:
    - family: metaplusmedium
      fonts:
        - asset: assets/fonts/metaplusmedium.ttf

